### PR TITLE
Infinite scroll for Epub reader

### PR DESCRIPTION
**Pull request by aladmit**
PDF and EPUB readers behave differently at the moment. RDF shows a document as an infinite scroll, then EPUB shows a document page by page. I think they should work identically by default. This PR enables scroll view for EPUB.

## Current problem
I've made changes directly in epub.js demo dir only because I didn't find a way to patch it from the plugin codebase. Is it possible? Could you give a hint on how to do that?

### Before
Screenshot 2022-01-17 at 08 04 23

### After
Screenshot 2022-01-17 at 08 01 45

### CODE REVIEW

**Comment by elias-sundqvist** [comment]
If changing the code to the demo directly is the only solution, that's ok. 

You should add a description of the changes to `Modified Resources.md`, though. That will remind me to reapply these changes if I update the epub reader in the future.

**Comment by elias-sundqvist** [comment]
Also, not sure if it can be easily done, but maybe this should be a setting? 

I also prefer continuous scrolling, but maybe some people prefer pagination?

**Comment by aladmit** [comment]
Agree, this should be a setting, but I don't see how I can pass params from plugin to `reader.js`. Maybe we can pass them as a part of the URL to the frame and then parse in `readers.js` 🤔  What do you think? Is this a good solution, or is there a better one I don't see?

**Comment by elias-sundqvist** [comment]
If it's possible to change the mode after loading the epub, there might be a better way. 

You should be able to use the `onload` prop of the `EpubAnnotation` component to get a reference to the iframe with the epub when it has loaded. (See [annotatorView.tsx:100](https://github.com/aladmit/obsidian-annotator/blob/28c5b6595d3e7de31c37ac12b31040618244b6a4/src/annotatorView.tsx#L100))

You should then be able to access the `rendition` object by doing  `(iframe.contentWindow as any).rendition`.
This is because I save the rendition object to the `window` object of the iframe, [here](https://github.com/aladmit/obsidian-annotator/blob/28c5b6595d3e7de31c37ac12b31040618244b6a4/resources/cdn.hypothes.is/demos/epub/epub.js/js/reader.js#L20). If there is anything else you need to expose, you could to it in a similar way.

**Comment by aladmit** [comment]
> If it's possible to change the mode after loading the epub, there might be a better way.

Yeap, I had this idea too, no luck. We need to create a reader with the right params from the start :(
http://epubjs.org/documentation/0.3/#rendition

To make 'scroll' work, we need to change `manager` and `flow` params. API allows changing only `manager`.

> You should be able to use the onload prop of the EpubAnnotation
Oh! I missed that, thank you 🔥  I tried to use `onload` prob in `defineGenericAnnotation`, but it was too dirty because of `if something == epub` conditions.

I exposed the whole `reader.js` to `window`, added an arg, and executed it from `onload`. Looks okay for now, but it feels like at some moment we are going to have a lot of params and modifications for epub, and it will be easier to have our own `reader.js` than support this one.

**Comment by aladmit** [comment]
Now it's possible to choose EPUB reader mode in settings, but there are a few more things that need to be done:
2. **show annotation** link work incorrectly with Scroll view
3. Remove page separator in Scroll view
4. Remove arrows in Scroll view
5. Increase reader size in Scroll view

**Comment by aladmit** [comment]
@elias-sundqvist Hided page separator and arrows, scrolling looks good now 👌🏻 

About reader size. It feels like a complex change because if I increase the block size in css, it breaks scrolling to other pages and pagination view. So, I suggest we do that in different PR.

And I don't want to fix **show annotation** links in this PR because they work incorrectly in master branch too :(

Screenshot 2022-01-21 at 19 32 20

**Comment by elias-sundqvist** [comment]
That's reasonable. I'll try compiling and running the code on my device, and if all looks good I'll merge it. 👍

**Comment by elias-sundqvist** [comment]
I'd say this is good enough. there are some minor issues, but we can deal with them separately. 

* If you switch chapters in the sidebar quickly, the infinite scrolling breaks. 
* Sometimes parts of the pages get cropped out
* sometimes an annotation sidebar shows up "inside" the epub page. (this issue is also present in the master branch)

**Pull request merged**
